### ISSUE TITLE
EVO 2.0 Alpha - problem with module extras and displaying DocLister in front-end

### ISSUE THREAD

**Issue by modwebpl** [evolution-cms/evolution#1064]
Error when I try install DocLister from module Extras:
![Zrzut ekranu 2019-04-18 o 16 13 55](https://user-images.githubusercontent.com/35030936/56367671-142f3d00-61f6-11e9-9682-8ad1622426c3.png)

Error when I try to display simple "page title" like this: DocLister? &documents='2' &tpl='@CODE:[+pagetitle+]'

![Zrzut ekranu 2019-04-18 o 16 21 06](https://user-images.githubusercontent.com/35030936/56367764-450f7200-61f6-11e9-8caa-470375377156.png)

**Comment by dmi3yy** [comment]
You need put file siteManager.php from evo 1.4  I will fix this soon


От 18 апреля 2019 г. в 17:23:20, Paweł Kołodziejczak (
notifications@github.com) написал:

Error when I try install DocLister from module Extras:
[image: Zrzut ekranu 2019-04-18 o 16 13 55]
<https://user-images.githubusercontent.com/35030936/56367671-142f3d00-61f6-11e9-9682-8ad1622426c3.png>

Error when I try to display simple "page title" like this: DocLister?
&documents='2' &tpl='@code <https://github.com/code>:[+pagetitle+]'

[image: Zrzut ekranu 2019-04-18 o 16 21 06]
<https://user-images.githubusercontent.com/35030936/56367764-450f7200-61f6-11e9-8caa-470375377156.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/evolution-cms/evolution/issues/1064>, or mute the thread

**Comment by modwebpl** [comment]
Ok thanks a lot, so i cant wiat until next update will be released :)
