### ISSUE TITLE
Подключение скриптов в админке по http

### ISSUE THREAD

**Issue by ultraviolet** [evolution-cms/evolution#1066]
1.4.8. Сайт https, в настройках радиобатон установлен на https, [(site_url)] показывает адрес сайта с https.
При загрузке документа из дерева ресурсов, стили и скрипты из папок /assets/tvs/multitv/ и /assets/plugins/pagebuilder/ (возможно, и другие ТВ, плагины, у которых есть подключаемые ресурсы) подключаются по http https://monosnap.com/file/R6Q9HEqSX8IVdDTeS9Q7Ncdazg3Q6k . Такие ошибки в консоли Хрома https://monosnap.com/file/iHC2lkQHNvvSdPudV7SPk4I1enRpBo . 

В результате, в админке нельзя управлять multitv и pagebuilder https://monosnap.com/file/q8D84iGoUVprHXiodMGh5iBn2CRHDD . А если загрузить через Фаерфокс и временно разрешить "небезопасный контент", то соотв. скрипты и стили загружаются, и проблемы нет.

Причём, несколько версий назад не наблюдал такой беды, и с тех пор вроде не было изменений на сайте, которые бы могли привести к подобному.

**Comment by dmi3yy** [comment]
Это проблема с настройками сервера в 1.4.9 этот момент поправили на части
серверов. В целом можно исправить руками в файле config.inc.php там где
проверка на https
Указать просто принудительно что https
В целом в админке галочка http или https вообще нигде не используется


От 19 апреля 2019 г. в 15:33:16, ultraviolet (notifications@github.com)
написал:

1.4.8. Сайт https, в настройках радиобатон установлен на https,
[(site_url)] показывает адрес сайта с https.
При загрузке документа из дерева ресурсов, стили и скрипты из папок
/assets/tvs/multitv/ и /assets/plugins/pagebuilder/ (возможно, и другие ТВ,
плагины, у которых есть подключаемые ресурсы) подключаются по http
https://monosnap.com/file/R6Q9HEqSX8IVdDTeS9Q7Ncdazg3Q6k . Такие ошибки в
консоли Хрома https://monosnap.com/file/iHC2lkQHNvvSdPudV7SPk4I1enRpBo .

В результате, в админке нельзя управлять multitv и pagebuilder
https://monosnap.com/file/q8D84iGoUVprHXiodMGh5iBn2CRHDD . А если загрузить
через Фаерфокс и временно разрешить "небезопасный контент", то соотв.
скрипты и стили загружаются, и проблемы нет.

Причём, несколько версий назад не наблюдал такой беды, и с тех пор вроде не
было изменений на сайте, которые бы могли привести к подобному.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/evolution-cms/evolution/issues/1066>, or mute the thread

**Comment by ultraviolet** [comment]
Обновился до 1.4.х develop, не помогло. Также, указал в config.inc.php 
`$site_url = 'https://';`
вместо 
`$site_url = ((isset ($_SERVER['HTTPS']) && ( (strtolower($_SERVER['HTTPS']) == 'on') || ($_SERVER['HTTPS']) == '1')) || $_SERVER['SERVER_PORT'] == $https_port || $secured) ? 'https://' : 'http://';`
вот так теперь выглядит https://monosnap.com/file/sxm3gOhJMMeL7ljD1YbWLqlQ0CuEgQ
Тоже не помогло.

**Comment by 64j** [comment]
httaccess правьте, чекбокс в админке это не решает.

**Comment by ultraviolet** [comment]
htaccess по умолчанию, кроме этого:
```
# 301 to https
RewriteCond %{HTTP:SSL} !=1 [OR]
RewriteCond %{HTTP_HOST} ^www.site.ru$ [NC]
RewriteRule (.*) https://site.ru/$1 [L,R=301]
```
Закомментировал, проверил, не помогает, раскомментировал. Не знаю что там ещё можно поправить.

**Comment by 64j** [comment]
Так у вас htaccess не отрабатывает.

**Comment by ultraviolet** [comment]
Что именно не отрабатывает? (если что , site.ru в качестве подстановки, а не реальный домен)

**Comment by 64j** [comment]
@ultraviolet 
Как вы делаете перенаправление с http на https ?

**Comment by ultraviolet** [comment]
С пом. htaccess https://github.com/evolution-cms/evolution/issues/1066#issuecomment-484981690 (# 301 to https)

**Comment by 64j** [comment]
Судя по скринам из первого поста, он не работает.
Попробуйте другие правила поставить или скиньте доступ к сайту в телеграм.


Вариант 1  
RewriteCond %{SERVER_PORT} ^443$ [OR] 
RewriteCond %{HTTPS} =on 
RewriteRule ^(.*)$ http://site.ru/$1 [R=301,L]

Вариант 2  
RewriteCond %{HTTPS} =on 
RewriteRule ^(.*)$ http://%{HTTP_HOST}/$1 [R=301,L]

Вариант 3  
RewriteCond %{HTTPS} =on 
RewriteRule ^.*$ http://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

Вариант 4  
RewriteCond %{SERVER_PORT} 443 
RewriteRule ^.*$ http://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

Вариант 5  
RewriteCond %{HTTPS} =on 
RewriteRule ^.*$ http://%{SERVER_NAME}%{REQUEST_URI}

Вариант 6  
RewriteCond %{HTTP:SSL} =1 [NC] 
RewriteRule ^(.*)$ http://%{HTTP_HOST}/$1 [R=301,L] 
RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC] 
RewriteRule ^(.*)$ http://%1%{REQUEST_URI} [R=301,L]

Вариант 7  
RewriteCond %{HTTP_HOST} !^site\.ru$ [NC] 
RewriteRule ^(.*)$ http://site.ru/$1 [R=301,L] 

Вариант 8  
RewriteCond %{HTTP:SSL} =1 [NC] 
RewriteRule ^(.*)$ http://%{HTTP_HOST}/$1 [R=301,L] 
RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC] 
RewriteRule ^(.*)$ http://%1%{REQUEST_URI} [L,R=301] 

Вариант 9  
RewriteCond %{HTTP:X-Forwarded-Proto} =https 
RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301] 

Вариант 10  
RewriteCond %{SERVER_PORT} ^443$ [OR] 
RewriteCond %{ENV:HTTPS} =on 
RewriteRule ^(.*)$ http://site.ru/$1 [R=301,L]

Попробуем ещё вариант - вместо %{HTTPS} указать %{ENV:HTTPS}

Вариант 11  
RewriteCond %{ENV:HTTPS} on 
RewriteRule ^.*$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

Вариант 12  
RewriteCond %{ENV:HTTPS} On 
RewriteRule ^.*$ http://%{SERVER_NAME}%{REQUEST_URI}

**Comment by ultraviolet** [comment]
@64j , редиректы http->https вроде работают корректно с директивами из https://github.com/evolution-cms/evolution/issues/1066#issuecomment-484981690 . Это видно по всевозможным проверяльщикам кода ответа сервера и визуально в браузере, если вбить http://... Тем не менее, проверил большинство директив, предложенных вами (только "отзеркаленных", т.к . соотв. директивы для редиректа https->http, а надо наоборот), и получил те же результаты.

А куда именно в Телеграм можно скинуть доступы - вам в личку?

**Comment by 64j** [comment]
@ultraviolet 
Да, со мной можно связаться на официальном канале https://t.me/evolutioncms

**Comment by 64j** [comment]
@mnoskov

Михаил, посмотри.
Там пути с http подставлялись.

Поправил так.

![image](https://user-images.githubusercontent.com/4653189/56578270-e8390080-65d5-11e9-836f-61cd0105ad72.png)

**Comment by ultraviolet** [comment]
А для Мультитв частичная правка такая: в файле /assets/tvs/multitv/includes/multitv.class.php заменить ../ на $this->modx->config['site_url'] в нескольких местах. Всё вроде стало работать, только по нескольким картинкам в консоли выкидывается предупреждение.
