### ISSUE TITLE
Site doesn't work after update to 2.0

### ISSUE THREAD

**Issue by Sybrenb** [evolution-cms/evolution#1304]
I followed the steps as described by Dmi3yy to update my 1.4.10 site to 2.0:
https://github.com/evolution-cms/evolution/releases/tag/2.0

But, I got the following error message after the update and my site doesn't work anymore:
ERROR: Too many forward attempts!

I also can't login into the manager anymore.

What could be wrong?

**Comment by Dmi3yy** [comment]
try check htaccess 

ERROR: Too many forward attempts! - its not problems with update

**Comment by BBloke** [comment]
I've been working on updating to v2.0 and whilst checking things out I found somethings just had to be changed for the better.

In order to get to v2.0 I had to stop using AjaxSearch and WebLoginPE in favour for evoSearch and FormLister.

I'm not sure why you cannot log in to the manager but I thing the too many forward attempts is due to WebLoginPE.  It creates strange things.

The migration to v2.0 was pretty straight forward.
