### ISSUE TITLE
Quick Manager+ Unnecessary Button?

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#275]
On the right side of the QM+ bar there is a close button
![untitled](https://user-images.githubusercontent.com/1744687/31122043-4f9c9948-a832-11e7-9d8a-5ca197c3e140.png)
Is this button needed? It performs the same function as the button on the left side and takes up valuable space, particularly if custom buttons are added to the toolbar, or viewing on a smartphone.

**Comment by fourroses666** [comment]
the hamburger is not correct, to me it refers to a mobile navigation :o

**Comment by bossloper** [comment]
I think it is set as that to reflect the same icon used in the backend manager to minimise/expand the left menu tree... as effectively it is performing similar functionality of expanding/contracting and is located in a similare place on the interface. But yes in does shout mobile menu to me too. Maybe a different icon is needed for both the qm+ and backend manager. There are font awsome expand and compress icons?:
http://fontawesome.io/icon/expand/
http://fontawesome.io/icon/compress/

**Comment by Nicola1971** [comment]
instead of the X icon we can add the manager username (like in backend)

@bossloper yes the hamburger icon should reflect the manager menu icon.
@fourroses666  looks like a mobile menu to me too, but the font awesome expand icon looks more like a "full screen" icon

another wrong icon in the manager (for me) is the preview site icon:
![download](https://user-images.githubusercontent.com/7342798/31135020-1a64e2e4-a864-11e7-9c3e-106cabcd0990.png)

when in whole manager the preview icon is an "eye"
![download](https://user-images.githubusercontent.com/7342798/31135058-388d9d38-a864-11e7-8e99-6cd093529c94.png)
![download](https://user-images.githubusercontent.com/7342798/31135120-5feea304-a864-11e7-9f87-cc050fae99d5.png)
![download](https://user-images.githubusercontent.com/7342798/31135171-8996dce4-a864-11e7-9393-4155a5234435.png)

**Comment by bossloper** [comment]
@Nicola1971 - while talking about preview icon and trying not to get too off topic! :-)
It would be nice if the manager preview icon opened in the same window/tab. If the icon was in a similar horizontal position on the top bar in manager and qm+ it would then be a nice quick switch from manager to front-end and back without creating more tabs as it does now.

**Comment by bossloper** [comment]
... there are also old button styles on the qm+ resource editor window:
![untitled](https://user-images.githubusercontent.com/1744687/31136829-2fd03438-a861-11e7-9a96-486cf3cd7b98.png)

**Comment by Nicola1971** [comment]
![fireshot capture 222 - home _ my evolution site - http___localhost_evo14_](https://user-images.githubusercontent.com/7342798/31236845-898e0b7c-a9f5-11e7-86d7-d5b335754499.png)
