### ISSUE TITLE
admin password on installation does not like special characters

### ISSUE THREAD

**Issue by boflor** [evolution-cms/evolution#290]
When setting an ampersand sign (&) in the admin password during installation, the admin can not log in the backend after the installation.

**Comment by risingisland** [comment]
This is due to a bug that has been around for a while...
https://github.com/evolution-cms/evolution/issues/48

**Comment by bossloper** [comment]
... so can close this one as a duplicate?

**Comment by modxuser** [comment]
I originaly opend the post you have linked to, it was in the old Evo Git account, @dmi3yy transfered it over.

The problem here is that @Deesen did fix the bug, but it has since cropped up again and since then no-longer been looked at.

https://github.com/modxcms/evolution/commit/73b12b1ef4ef95eda24bcad00a402a9777a92f54

**Comment by risingisland** [comment]
Also, if you try to update any password and it contains "&", you  can no longer login.

**Comment by dmi3yy** [comment]
done
