### ISSUE TITLE
eForm больше не работает?

### ISSUE THREAD

**Issue by webber12** [evolution-cms/evolution#371]

**Comment by dmi3yy** [comment]
Работает просто его нет по умолчанию с версии 1.4 можно скачать с екстрас

Отправлено с iPhone

**Comment by webber12** [comment]
Странно, я вызвал его как обычно и все было нормально, пока не дошла очередь до отправки письма. Посыпались ошибки сниппетов, которых на этой странице даже не было. Поставил на шаблон _blank, где вообще больше ничего не было - аналогичная ситуация. Пока идет валидация - все нормально, как только валидация прошла и началась отправка письма - ошибка в сниппете вроде [[aDate]] или [[if]], которые есть на сайте, но на данной пустой странице с формой не присутствуют. Такое ощущение, что эту форму пытается прогнать через 404 или главную страницу и не может найти при парсинге какие-то параметры для сниппетов, которые расположены там.

**Comment by dmi3yy** [comment]
Понял проверю

Отправлено с iPhone

**Comment by webber12** [comment]
Кстати, eForm при обычной ошибке Could not instantiate mail function. зачем то вываливает в протокол событий и весь documentObject и весь конфиг и все чанки из кэша. При этом вываливаясь в ошибку какого-нибудь левого сниппета. Может это как-то связано друг с другом.

Да и вообще неплохо бы проверить этот modxMailer, т.к. при простом подключении файла обычно вся почта уходит как надо, а через loadExtension в 90% случаев на бел хостинге письма уходить не хотят, видимо за счет каких-то левых заголовков, которые он устанавливает.

**Comment by dmi3yy** [comment]
Планирую на днях обновить phpmailer и заодно проверю коректную работу
FormLister и eForm
обычно через апи и через smtp




От 22 ноября 2017 г. в 11:57:01, webber12 (notifications@github.com)
написал:

Кстати, eForm при обычной ошибке Could not instantiate mail function. зачем
то вываливает в протокол событий и весь documentObject и весь конфиг и все
чанки из кэша. При этом вываливаясь в ошибку какого-нибудь левого сниппета.
Может это как-то связано друг с другом.

Да и вообще неплохо бы проверить этот modxMailer, т.к. при простом
подключении файла обычно вся почта уходит как надо, а через loadExtension в
90% случаев на бел хостинге письма уходить не хотят, видимо за счет
каких-то левых заголовков, которые он устанавливает.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evolution-cms/evolution/issues/371#issuecomment-346300475>,
or mute the thread

**Comment by webber12** [comment]
Не забыть loadExtension(modxMailer) проверить на предмет этих левых заголовков :)
Надоело уже лазить в эту еформу и постоянно менять там строчку
`$modx->loadExtension('MODxMailer');`
на 
```
require_once MODX_BASE_PATH . MGR_DIR . '/includes/controls/class.phpmailer.php';
$modx->mail = new PHPMailer();
$modx->mail->CharSet = $modx->config['modx_charset'];
```

Иначе в 90% случаев получаю ошибку Could not instantiate mail function - подозреваю именно заголовки.

**Comment by dmi3yy** [comment]
оке проверю ну и как сделаю напишу.


От 22 ноября 2017 г. в 12:05:02, webber12 (notifications@github.com)
написал:

Не забыть loadExtension(modxMailer) проверить на предмет этих левых
заголовков :)
Надоело уже лазить в эту еформу и постоянно менять там строчку
$modx->loadExtension('MODxMailer');
на

require_once MODX_BASE_PATH . MGR_DIR .
'/includes/controls/class.phpmailer.php';
$modx->mail = new PHPMailer();
$modx->mail->CharSet = $modx->config['modx_charset'];

Иначе в 90% случаев получаю ошибку Could not instantiate mail function -
подозреваю именно заголовки.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/evolution-cms/evolution/issues/371#issuecomment-346302611>,
or mute the thread

**Comment by dmi3yy** [comment]
Сейчас займусь обновлением phpmailer https://github.com/evolution-cms/evolution/issues/302
там проверю. 
так же замечу что eForm не работает на php 7.2 если что

**Comment by Nicola1971** [comment]
> Also note that eForm does not work on php 7.2 if that

Interesting. As an important old default snippet, I think we need to add this info in Extras.To allow peole to choose switch to FormLister or mantain a lower php version.
and avoid alot of github issue about it :smile:
