### ISSUE TITLE
The function "Export a site" not working

### ISSUE THREAD

**Issue by Rising13** [evolution-cms/evolution#379]
Now faced with the problem. 
I tried to run export standard button "Export site". 
The output I have created a completely empty file weighing in at zero bytes.
Tested on different versions, 1.2.1 and 1.4.0 RC2

Столкнулся сейчас с проблемой. 
Попробовал запустить экспорт сайта стандартной кнопкой "Экспортировать сайт". 
На выходе у меня создались совершенно пустые файлы весом в ноль байт.
Проверял на разных версиях - 1.2.1 и 1.4.0 RC2
![screenshot_8](https://user-images.githubusercontent.com/21079372/33200886-75dd26c4-d107-11e7-863b-20656cf4001e.png)

**Comment by modxuser** [comment]
I just tested this as well on localhost on a windows machine running a variety of Evo installs. I generaly dont use a suffix and the tests have been run as such:

In 1.0.7 you can export and choose a prefix and a suffix, which means you dont have to mess around with the main config.

In 1.0.15 + 1.2 you can export, but the files do not have a suffix if not pre-defined in the config. So the exported files end up like "index" instead of "index.html"

1.2 + 1.2.1 doesn't export files when they are also used as folders e.g "About Us" could be a file and a folder, if it's a file and a folder it exports it only as a folder, the file is therefore lost, which means if you have previously marked a file as a container and dont use it as one, in the export you get an empty folder and the file is lost - 1.0.15 adds the file as an "index" inside the folder.

**Comment by bossloper** [comment]
can close as referenced here?: https://github.com/evolution-cms/evolution/issues/481

**Comment by Deesen** [comment]
Yes #481 seems to provide the solution.
