### ISSUE TITLE
Doclister / Formlister - Major Issues

### ISSUE THREAD

**Issue by modxuser** [evolution-cms/evolution#507]
Whilst testing Formlister I found that it has dependencies that are not written down in any documentation I have been able to find.

By simply renaming the Doclister folder, Formlister no-longer works

Another side effect of renaming the folder is that all snippets that are dependant on Doclister change their snippet calls - section "Snippet code (php)" 

**Example - DLCrumbs**

Original:
```
<?php
return require MODX_BASE_PATH.'assets/snippets/DocLister/snippet.DLCrumbs.php';
```
After renaming the Doclister folder
```
<?php
File not found: assets/snippets/DocLister/snippet.DLCrumbs.php
```
![dlcrumbs](https://user-images.githubusercontent.com/1859868/36253119-f69a77c8-1246-11e8-9430-06633be047fa.png)

**Comment by modxuser** [comment]
To get the snippets back up and running I had to delete both snippet folders and copy them over from another install

**Comment by Pathologic** [comment]
FormLister (like many other components) uses DLTemplate class of DocLister. I'll move it to the lib folder in future. 
"File not found: " is the output of FileSource plugin, enabled by default. Be careful with this plugin, because if you change duplicated snippets/plugins in manager it will overwrite the file of the original one.

**Comment by modxuser** [comment]
OK, thanks

I have removed the plugin, I have never had it installed in the past
