### ISSUE TITLE
Is 'Top how many' system option used?

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#625]
Is this system option under 'Site' tab used anywhere, if not can it be removed?
![untitled](https://user-images.githubusercontent.com/1744687/38492081-c539675c-3be5-11e8-8921-5ff8513e42ad.png)

**Comment by dmi3yy** [comment]
yes not used (


От 9 апреля 2018 г. в 13:06:02, Mr B (notifications@github.com) написал:

Is this system option under 'Site' tab used anywhere, if not can it be
removed?
[image: untitled]
<https://user-images.githubusercontent.com/1744687/38492081-c539675c-3be5-11e8-8921-5ff8513e42ad.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/evolution-cms/evolution/issues/625>, or mute the thread
