### ISSUE TITLE
Question: Possible to set Save & Close by default?

### ISSUE THREAD

**Issue by risingisland** [evolution-cms/evolution#630]
When editing a resource is it possible to set Save & Close by default for all users?
(as opposed to Save and Continue Editing)

**Comment by fourroses666** [comment]
I personally like Continue more. 
And maybe when clicking on 'Close' then the Tab also disappears (1.4.x)?
Or an option to choose between close tab.

**Comment by risingisland** [comment]
Not using tabs, some clients find it confusing, not sure if it saved or not.
Thus, wondering if there was a setting for this that I was missing.

**Comment by risingisland** [comment]
Yes, I know. They prefer not to have them turned on because they dont know if it was saved or not.

**Comment by risingisland** [comment]
OK, I didnt know if I was just missing the option somewhere or maybe there was an easy solution.
Will close unless someone else has any tips.

**Comment by fourroses666** [comment]
Some understand these tabs and maybe some don't. I like them allot especially when developing.
-> A small yellow dot should show if its saved or not I guess. Turns green when its saved or when its not edited yet. Is an idea.

About your question default Save & Close default. My opinion about that is that I'm not sure.
Maybe your right and its the expected behaviour for resources. I think I'm used to Save & Continue.

**Comment by risingisland** [comment]
@fourroses666 Marc, nice idea about the dots to show whether it has been saved or not.
Possibly a Config./Interface & Features setting to choose default would be another idea. 
Both of which are out of my hands.

Personally, and as you mentioned, especially during development, I like the continue after save, but clients are a different matter.

Thanks for the input, will close for now.
