### ISSUE TITLE
Publishing/unpublishing a plugin does not update dropdown menu colour

### ISSUE THREAD

**Issue by bossloper** [evolution-cms/evolution#67]
The manager Plugins dropdown menu shows unpublished resources in red. 
If a plugin is published/unpblished then the dropdown menu does not update the colour accordingly - manager page needs to be refreshed for the new plugin colour status to be updated.

**Comment by dmi3yy** [comment]
#11
When you select a new TV in the top menu, the top menu remembers the position, and the selected item, when you create a new TV and then click on the top menu again, it shows the last position if you hover the mouse over other items, and then on the TV, Then in the third level all the elements will be updated, and your new one created.
This is done in order not to produce a heap of requests when you simply hover the mouse over menu items.
Also, if you pay attention there is a delay, so that the script understands that this is the section you need and only then made a request to the server.

**Comment by 64j** [comment]
https://monosnap.com/file/Dx0UJUGbbCSWfc51JBPZ8IXrOZNLZJ

**Comment by bossloper** [comment]
The screen-cast does not test the exact  issue.
Do not delete the plugin, just 'disable' aka unpublish it. Then you will see in the dropdown menu the plugin colour has not been updated to red.

**Comment by 64j** [comment]
https://monosnap.com/file/nWE64d6aXtkhZ6rcxXhPznJ8rJFg5C

**Comment by bossloper** [comment]
OK, I see now. Thanks Serg. That is close enough )
