### ISSUE TITLE
please bring the backup button back into the dashboard icons

### ISSUE THREAD

**Issue by nick0** [evolution-cms/evolution#736]
Hello,

With the 1.4.4 update, the icons on the main dashboard changed to this:
![dashboard-new](https://user-images.githubusercontent.com/1768308/41634228-eab05f5c-7481-11e8-9e6a-2965230e53b9.png)
with: new resource, new weblink, manage images, manage files, change password, logout

Previously it was this:
![dashboard-old](https://user-images.githubusercontent.com/1768308/41634260-0e4e676a-7482-11e8-82cd-af230ad4c2c7.png)
with: manager users, web users, modules, elements, backup, help.

I really miss the backup button. 

I wish there was a way to select which buttons are shown in that tab on the dashboard so I could put the back up button back?

Failing that, please put the backup button back in by default.

Thanks.

**Comment by bossloper** [comment]
You could write your own welcome widget as a plugin. I have totally replaced it with my own version that includes the manager users links (if the manager has privs) and lists active modules (if they have security to run them):

![untitled](https://user-images.githubusercontent.com/1744687/41642979-de61d480-7461-11e8-9bbb-a4b495fb0dc5.png)

It uses the 'OnManagerWelcomeHome' event.
You can hide/rename move existing widgets e.g.:

$e = &$modx->Event;
$widgets['security']['hide']='1';
$widgets['news']['cols']='col-sm-12';
$widgets['news']['menuindex']='4';  
$widgets['onlineinfo']['title']='Online Managers and Members';
$widgets['onlineinfo']['cols']='col-sm-12';
$widgets['recentinfo']['menuindex']='2';
$e->output(serialize($widgets));

or replace a widget e.g. make your own welcome widget:

$widgets['welcome'] = array(
            'menuindex' =>'1',
            'id' => 'welcome',
            'cols' => 'col-sm-12',
            'icon' => 'fa-home',
            'title' => $modx->config['site_name'].' (CMS by xxxxxxx)',
            'body' => $yourcustomwelcomehtmlhere,
            'hide'=>'0'
        );

Note you do need to make sure the plugin is last in the plugin execution order for the OnManagerWelcomeHome event otherwise Updater and OutdatedExtrasCheck plugins can reset the widgets it back to default.

**Comment by nick0** [comment]
Thanks @bossloper. I think that is beyond my limited programming skills without a step by step tutorial. Thanks for the assistance though, I appreciate it.

**Comment by dmi3yy** [comment]
I think we can add 2 more buttons like: 
- backup 
- elements
