### ISSUE TITLE
Evolution 1.4.5RC2 Does not work logo replacement

### ISSUE THREAD

**Issue by myindexlike** [evolution-cms/evolution#763]
on the login page of the admin area

"Login page logo image"

В админке отображается, а на странице входа нет.

**Comment by bossloper** [comment]
Cannot reproduce the issue (php 7.1):
![1](https://user-images.githubusercontent.com/1744687/42735083-6a8dcba6-8846-11e8-9a10-422ef706b878.png)
Logo is displayed:
![2](https://user-images.githubusercontent.com/1744687/42735085-6ced1f50-8846-11e8-8059-925f25226b0c.png)

**Comment by myindexlike** [comment]
![screenshot_8](https://user-images.githubusercontent.com/16356381/42735814-767efc56-8863-11e8-8e78-50dddf10704c.png)

PHP Version  5.6.31

**Comment by bossloper** [comment]
Just reverted to php 5.6.36 and it still displays custom login logo for me. Not sure what to suggest.

![1](https://user-images.githubusercontent.com/1744687/42735905-6a99637c-8854-11e8-93ed-a492ac4bc31f.png)

**Comment by bossloper** [comment]
I can now reproduce your issue. It is because you have system 'Color Scheme' set to 'everything is dark'. 
![untitled](https://user-images.githubusercontent.com/1744687/42750019-9d43fb8c-88dd-11e8-9989-6b5c1ac8891e.png)
If you pick any other scheme the login logo will will work correctly. I am not even sure those system color scheme options have been fully implemented yet, though someone may correct me on that.

**Comment by myindexlike** [comment]
Thank you!
Indeed, changing the topic to light it became true to work
