### ISSUE TITLE
DBAPI getValue returns false instead of null with an empty resultset

### ISSUE THREAD

**Issue by TimGS** [evolution-cms/evolution#876]
Previously to https://github.com/evolution-cms/evolution/commit/782cff3468cf6dfe31efabfae07a6fcd16b5fafb#diff-b4aaf6d84f946d987c70c8bcf80c86ce DBAPI::getValue() returned null if the query returned no rows.

Calling code that checks for this would previously check for null e.g. 

`$v = $modx->db->getValue($rs);
if (is_null($v)) { ...`

Note that `if (!$v) {...` would be incorrect if the resultset could be non-empty but containing '0'.

Code that checks for null will now fail as $v will be false.

Bug noted whilst upgrading a site which included such code (the client was upgrading it, encountered this problem, and asked me to investigate).

Workaround is obviously to check for false in addition to null, but it would be better if the DBAPI functions remained consistent with respect to previous behaviour.

**Comment by AgelxNash** [comment]
Thanks for the feedback!

I think that the previous behavior was not correct. There is no point in maintaining backward compatibility, since This is a DBAPI code architecture error.

So, for example, we have a table
![image](https://user-images.githubusercontent.com/1748872/47789821-74f5b680-dd37-11e8-936a-5ff887bb9d17.png)
And some small script for tests
```php
$table = $modx->getFullTableName('test');
$tests = [
    1, 2, 3, 4
];

foreach ($tests as $id) {
    $query = $modx->db->query("SELECT `content` FROM " . $table . " WHERE `id` = " . (int)$id);
    $value = $modx->db->getValue($query);
    var_dump($value);
}
```

### Old method
```
NULL
string(0) ""
string(4) "test"
NULL
```
It's not correct. Because we don’t really know if record 1 and 4 exist. This may be important for the application.

### New method
```
bool(false)
string(0) ""
string(4) "test"
bool(false)
```
It's again not correct

### Current method after refactoring https://github.com/evolution-cms/evolution/commit/917cdb6f9203d7770234394326ef2d11d299cb88
```
NULL
string(0) ""
string(4) "test"
bool(false)
```
Now we can split the existing record and non-existent...


_@TimGS Can you try the package [agelxnash/modx-evo-database](https://github.com/AgelxNash/modx-evo-database)? if you have any time and some interests:-)_

**Comment by TimGS** [comment]
Your point is good and I agree that the new return values are inherently 'better'.

However they will break some sites (hence my involvement) which I think is more of an 'evil' than having an ambiguity in whether a db value is stored as NULL or the resultset is empty. It's easier to resolve that ambiguity (if required) than having a client wondering why their 'upgraded' site is broken, and having a developer have to track down the issue.

Obviously up to you how you balance these issues though.

**Comment by AgelxNash** [comment]
I'm sorry you had to deal with this problem. But abort backward compatibility is sometimes necessary to move forward.

Thank you for testing and ticket. Preparing for release of version 1.4.6 we will tell about this compatibility issue. This will help to avoid problems when updating.
